### ISSUE TITLE
How to build funcsfa?

### ISSUE THREAD

**Issue by aurelien-naldi** [NKI-CCB/funcsfa#1]
I am trying to create a conda package for funcsfa but I can't build it. I added numpy, openblas, lapack and a c compiler to the build dependencies, it does compile the main c file but then fails while looking for "funcsfa-c/build/version.c".

According to the name of the file, I suppose it seems to be a generated file, but setup.py does not generate it properly. Is something missing in your git repository or should I ran an extra command to build it?

**Comment by tychobismeijer** [comment]
Thanks for reporting this. The file version.c file has become obsolete, so I removed all references to it. I could now install the package with pip in Python 3.6.

Let me know how you are doing with conda package. I'm not a conda user, but this would be very useful to other people wanting to install the package :-).

**Comment by aurelien-naldi** [comment]
Thanks for the quick fix, it works fine now!
For now we are experimenting a bit, but we will be happy to share the conda recipe with you or to directly propose its inclusion in the bioconda channel.
